import datetime
from typing import List

from fpdf import FPDF

_SEV_COLORS = {
    "critical": (220, 38, 38),
    "high":     (234, 88, 12),
    "warning":  (161, 98, 7),
    "info":     (37, 99, 235),
}


def generate_review_pdf(review_run, findings: List) -> bytes:
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    result = review_run.result or "unknown"
    passed = result == "success"

    # ── Header ────────────────────────────────────────────────────────────────
    if passed:
        pdf.set_fill_color(22, 163, 74)
    else:
        pdf.set_fill_color(220, 38, 38)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Helvetica", "B", 18)
    label = "PASSED" if passed else "FAILED"
    pdf.cell(0, 13, f"Code Review Report - {label}", fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.set_fill_color(40, 40, 40) if not passed else pdf.set_fill_color(16, 120, 56)
    subtitle = f"{review_run.task_key or 'N/A'}  ·  {review_run.sprint_name or 'N/A'}"
    pdf.cell(0, 8, subtitle, fill=True, align="C", new_x="LMARGIN", new_y="NEXT")

    pdf.ln(5)

    # ── Details table ────────────────────────────────────────────────────────
    _section_title(pdf, "Details")

    meta_rows = [
        ("Task",              review_run.task_key or "-"),
        ("Sprint",            review_run.sprint_name or "-"),
        ("Source Branch",     review_run.source_branch or "-"),
        ("Target Branch",     review_run.target_branch or "-"),
        ("Actor",             review_run.actor_username or "-"),
        ("Commit SHA",        (review_run.commit_sha or "-")[:12]),
        ("Risk Level",        (review_run.risk_level or "-").upper()),
        ("Files Analyzed",    str(review_run.total_files_analyzed or 0)),
        ("Total Findings",    str(review_run.total_findings or 0)),
        ("Blocking Findings", str(review_run.blocking_findings_count or 0)),
    ]
    pdf.set_font("Helvetica", "", 10)
    for label, value in meta_rows:
        pdf.set_text_color(107, 114, 128)
        pdf.cell(48, 6, label + ":", new_x="RIGHT", new_y="TOP")
        pdf.set_text_color(17, 24, 39)
        pdf.cell(0, 6, str(value), new_x="LMARGIN", new_y="NEXT")

    pdf.ln(4)

    # ── Summary ───────────────────────────────────────────────────────────────
    _section_title(pdf, "Summary")
    pdf.set_font("Helvetica", "", 10)
    pdf.set_text_color(55, 65, 81)
    pdf.multi_cell(0, 6, review_run.report_summary or "No summary available.")
    pdf.ln(4)

    # ── Decision Reason ───────────────────────────────────────────────────────
    if review_run.decision_reason:
        _section_title(pdf, "Decision Reason")
        pdf.set_font("Helvetica", "", 10)
        pdf.set_text_color(55, 65, 81)
        pdf.multi_cell(0, 6, review_run.decision_reason)
        pdf.ln(4)

    # ── Findings table ────────────────────────────────────────────────────────
    _section_title(pdf, f"Findings ({len(findings)})")

    if findings:
        col_w = [65, 18, 25, 82]
        headers = ["File", "Sev.", "Category", "Issue"]

        pdf.set_font("Helvetica", "B", 9)
        pdf.set_fill_color(241, 245, 249)
        pdf.set_text_color(55, 65, 81)
        pdf.set_draw_color(226, 232, 240)
        for i, h in enumerate(headers):
            pdf.cell(col_w[i], 7, h, border=1, fill=True)
        pdf.ln()

        pdf.set_font("Helvetica", "", 8)
        for f in findings[:50]:
            sev = (f.severity or "info").lower()
            r, g, b = _SEV_COLORS.get(sev, (107, 114, 128))

            file_str = f.file_path or "-"
            if f.line_number:
                file_str += f":{f.line_number}"
            if len(file_str) > 40:
                file_str = "..." + file_str[-38:]

            pdf.set_text_color(107, 114, 128)
            pdf.cell(col_w[0], 6, file_str, border=1)

            pdf.set_text_color(r, g, b)
            pdf.cell(col_w[1], 6, sev.upper(), border=1)

            pdf.set_text_color(55, 65, 81)
            cat = (f.category or "-")[:14]
            pdf.cell(col_w[2], 6, cat, border=1)

            issue = f.issue or "-"
            if len(issue) > 52:
                issue = issue[:49] + "..."
            pdf.cell(col_w[3], 6, issue, border=1)
            pdf.ln()
    else:
        pdf.set_font("Helvetica", "I", 10)
        pdf.set_text_color(107, 114, 128)
        pdf.cell(0, 8, "No findings.", new_x="LMARGIN", new_y="NEXT")

    # ── Footer ────────────────────────────────────────────────────────────────
    pdf.ln(10)
    pdf.set_font("Helvetica", "I", 8)
    pdf.set_text_color(156, 163, 175)
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    pdf.cell(0, 6, f"Generated by ACRP  ·  {ts}", align="C", new_x="LMARGIN", new_y="NEXT")

    return bytes(pdf.output())


def _section_title(pdf: FPDF, title: str) -> None:
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(17, 24, 39)
    pdf.cell(0, 8, title, new_x="LMARGIN", new_y="NEXT")
    pdf.set_draw_color(209, 213, 219)
    pdf.line(pdf.l_margin, pdf.get_y(), pdf.w - pdf.r_margin, pdf.get_y())
    pdf.ln(3)
